Zeniths/src/Zeniths.Web/Areas/Auth/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Zeniths.Auth.Service;
using Zeniths.Auth.Utility;
using Zeniths.Extensions;
using Zeniths.Helper;
using Zeniths.Utility;

namespace Zeniths.Web.Areas.Auth.Controllers
{
    [Authorize]
    public class SystemController : AuthBaseController
    {
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(string account, string password)
        {
            var userService = new SystemUserService();
            var result = userService.Login(account, password);
            if (result.Success) //登陆成功
            {
                FormsAuthentication.SetAuthCookie(account, false);
                return Json(new { success = true, message = "登陆成功", url = "/" });
            }
            return Json(result);
        }

        [AllowAnonymous]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            OrganizeHelper.Logout();
            return RedirectToAction("Login");
        }

        //[ZenithsAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult GetMenuTree()
        {
            var service = new SystemMenuService();
            var menus = service.GetEnabledList();
            var nodes = TreeHelper.Build(menus, p => p.ParentId == 0, (node, instace) =>
            {
                node.IconCls = instace.WebCls;
                node.Url = instace.WebUrl;
                if (node.Children != null)
                {
                    node.State = instace.IsExpand ? TreeNodeState.Open : TreeNodeState.Closed;
                }
            });
            return Json(nodes);
        }

        public ActionResult GetCurrentUser()
        {
            return Json(OrganizeHelper.GetCurrentUser());
        }

        public ActionResult WebIcons()
        {
            return View();
        }

        public ActionResult Files(string resName, string resId,bool allowDelete = false)
        {
            ViewBag.allowDelete = allowDelete;
            ViewBag.resName = resName;
            ViewBag.resId = resId;
            return View();
        }

        public ActionResult FilesGrid(string resName, string resId, bool allowDelete)
        {
            ViewBag.allowDelete = allowDelete;
            ViewBag.resName = resName;
            ViewBag.resId = resId;
            SystemFileService service = new SystemFileService();
            var list = service.GetList(resName, resId);
            return View(list);
        }

        public ActionResult FileDelete(string id)
        {
            SystemFileService service = new SystemFileService();
            var result = service.Delete(new[] { id.ToInt() });
            return Json(result);
        }
    }
}

Zeniths/src/Zeniths.Web/Areas/HR/Controllers/DailyReimburseController.cs
// ===============================================================================
// 正得信股份 版权所有
// ===============================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeniths.Collections;
using Zeniths.Hr.Entity;
using Zeniths.Hr.Service;
using Zeniths.Entity;
using Zeniths.Extensions;
using Zeniths.Helper;
using Zeniths.Utility;
using Zeniths.Hr.Utility;

namespace Zeniths.Web.Areas.Hr.Controllers
{
    /// <summary>
    /// 流程按钮控制器
    /// </summary>
    [Authorize]
    public class DailyReimburseController : HrBaseController
    {
        /// <summary>
        /// 服务对象
        /// </summary>
        private readonly DailyReimburseService service = new DailyReimburseService();
        private readonly DailyReimburseDetailsService detailsService = new DailyReimburseDetailsService();

        private object SessionData
        {
            get { return Session["DailyReimburseDetails"]; }
            set { Session["DailyReimburseDetails"] = value; }

        }

        /// <summary>
        /// 主视图
        /// </summary>
        /// <returns>视图模板</returns>
        public ActionResult Index()
        {

            return View();
        }

        /// <summary>
        /// 查看主视图
        /// </summary>
        /// <returns>视图模板</returns>
        public ActionResult AllIndex()
        {
            return View();
        }

        /// <summary>
        /// 表格视图
        /// </summary>
        /// <param name="name">按钮名称</param>
        /// <returns>视图模板</returns>
        public ActionResult Grid(string name)
        {
            var pageIndex = GetPageIndex();
            var pageSize = GetPageSize();
            var orderName = GetOrderName();
            var orderDir = GetOrderDir();
            var list = service.GetPageList(pageIndex, pageSize, orderName, orderDir, name,CurrentUserId);
            return View(list);
        }

       

        /// <summary>
        /// 表格视图
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult AllGrid(string name, string startDate, string endDate)
        {
            var pageIndex = GetPageIndex();
            var pageSize = GetPageSize();
            var orderName = GetOrderName();
            var orderDir = GetOrderDir();
            var list = service.GetAllPageList(pageIndex, pageSize, orderName, orderDir, name, startDate, endDate);
            return View(list);
        }

        /// <summary>
        /// 明细表格视图
        /// </summary>
        /// <returns></returns>
        public ActionResult DetailGrid(string dailyId)
        {
            var list = detailsService.GetList(dailyId.ToInt()); 
            return View(list);
        }
        

        /// <summary>
        /// 新增视图
        /// </summary>
        /// <returns>视图模板</returns>
        public ActionResult Create()
        {
            var entity = new DailyReimburse();
            entity.ReimburseDepartmentName = CurrentUser.DepartmentName;
            entity.ApplicantName = CurrentUser.Name;
            SessionData = null;
            ViewBag.Title = "添加日常费用报销";
            return EditCore(entity);
        }

        /// <summary>
        /// 编辑视图
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>视图模板</returns>
        public ActionResult Edit(string id)
        {
          
            var entity = service.Get(id.ToInt());
            var list = detailsService.GetList(id.ToInt());
            SessionData = list;
            ViewBag.Title = "编辑日常费用报销";
            return EditCore(entity);
        }


        /// <summary>
        /// 查看视图
        /// </summary>
        /// <param name="businessId">主键</param>
        /// <returns>视图模板</returns>
        public ActionResult Details(string businessId)
        {
           
            var entity = service.Get(businessId.ToInt());
            var list = detailsService.GetList(businessId.ToInt());
            SessionData = list;
            ViewBag.Title = "查看日常费用报销";
            return View(entity);
        }
        
        /// <summary>
        /// 查看视图
        /// </summary>
        /// <param name="businessId">主键</param>
        /// <returns>视图模板</returns>
        public ActionResult AllDetails(string businessId)
        {
            var entity = service.Get(businessId.ToInt());
            var list = detailsService.GetList(businessId.ToInt());
            SessionData = list;
            ViewBag.Title = "查看日常费用报销";
            return View(entity);
        }

        /// <summary>
        /// 数据编辑视图
        /// </summary>
        /// <param name="entity">实体对象</param>
        /// <returns>视图模板</returns>
        private ActionResult EditCore(DailyReimburse entity)
        {
            return View("Edit", entity);
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        /// <param name="entity">实体对象</param>
        /// <returns>返回JsonMessage</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(DailyReimburse entity)
        {
            var hasResult = service.Exists(entity);
            if (hasResult.Failure)
            {
                return Json(hasResult);
            }
            var result = new BoolMessage(false);
            
                entity.ReimburseDepartmentId = CurrentUser.DepartmentId;
                entity.ReimburseDepartmentName = CurrentUser.DepartmentName;
                entity.ApplicantId = CurrentUser.Id;
                entity.ApplicantName = CurrentUser.Name;
                entity.ApplicationDate = DateTime.Now.Date;
                entity.ApplySortNumber = service.GetYearAndMonthString() + "0000";
                entity.Title = "填写报销单";
                entity.IsFinish = false;
                entity.FlowId = "";
                entity.FlowInstanceId = "";
                entity.FlowName = "";
                entity.StepId = "";
                entity.StepName = "";
                entity.BudgetId = 0;
                entity.CreateUserId = CurrentUser.Id;
                entity.CreateUserName = CurrentUser.Name;
                entity.CreateDepartmentId = CurrentUser.DepartmentId;
                entity.CreateDepartmentName = CurrentUser.DepartmentName;
                entity.CreateDateTime = DateTime.Now;
                entity.ProjectSumMoney = 0;
                var curlist = (List<DailyReimburseDetails>)SessionData;
                foreach (var item in curlist)
                {
                    item.ReimburseId = entity.Id;
                    entity.ProjectSumMoney = entity.ProjectSumMoney + item.Amount;
                }
            if (entity.Id == 0)
            {
                result = service.Insert(entity, curlist);
            }
            else
            {
               
                //result = service.Update(entity, curlist);
            }

           
            return Json(result);
        }

        /// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>返回JsonMessage</returns>
        [HttpPost]
        public ActionResult Delete(string id)
        {
            var result = service.Delete(StringHelper.ConvertToArrayInt(id));
            return Json(result);
        }
        
    }
}

Zeniths/src/Zeniths.Web/Areas/WorkFlow/Controllers/FlowTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeniths.Extensions;
using Zeniths.Utility;
using Zeniths.WorkFlow.Service;
using Zeniths.WorkFlow.Utility;

namespace Zeniths.Web.Areas.WorkFlow.Controllers
{
    public class FlowTaskController : WorkFlowBaseController
    {
        private readonly FlowTaskService service = new FlowTaskService();

        /// <summary>
        /// 获取流程任务列表
        /// </summary>
        /// <param name="flowInstanceId">实例主键</param>
        /// <returns></returns>
        public ActionResult InstanceTasks(string flowInstanceId)
        {
            var list = service.GetTaskListByInstanceId(flowInstanceId);
            return View(list);
        }

        /// <summary>
        /// 获取流程图
        /// </summary>
        /// <param name="flowInstanceId"></param>
        /// <returns></returns>
        public ActionResult TaskImage(string flowInstanceId)
        {
            return View();
        }

        /// <summary>
        /// 获取待办任务
        /// </summary>
        /// <returns></returns>
        public ActionResult PendingTasks()
        {
            return View();
        }
        
        public ActionResult PendingTasksGrid(string flowId, string title)
        {
            var pageIndex = GetPageIndex();
            var pageSize = GetPageSize();
            var orderName = GetOrderName();
            var orderDir = GetOrderDir();
            var list = service.GetTaskPageList(pageIndex, pageSize, orderName, orderDir,
                CurrentUserId.ToString(), null, flowId, title, null, null, 0);
            return View(list);
        }

        /// <summary>
        /// 获取已办任务
        /// </summary>
        /// <returns></returns>
        public ActionResult HandledTasks()
        {
            return View();
        }

        public ActionResult HandledTasksGrid(string flowId,string title)
        {
            var pageIndex = GetPageIndex();
            var pageSize = GetPageSize();
            var orderName = GetOrderName();
            var orderDir = GetOrderDir();
            var list = service.GetBusinessTaskPageList(pageIndex, pageSize, orderName, orderDir,
               CurrentUserId.ToString(), null, flowId, title, null, null);
            return View(list);
        }

    }
}

Zeniths/src/Zeniths.Web/Areas/HR/Views/DailyReimburse/AllDetails.cshtml
@model DailyReimburse
@{
    var title = Html.GetCurrentStepName();
    Layout = "~/Views/Shared/_LayoutWorkflow.cshtml";
    var currentStep = Html.GetCurrentStep();
}

<div class="container-edit-zeniths" style="overflow-x: hidden; overflow-y: auto;">
    <form class="editform" action="@Html.GetFlowExecuteUrl()" method="POST" role="form">
        <div class="panel panel-default panel-zeniths" style="height: 685px; overflow-x: hidden; overflow-y: auto;">
            <div class="panel-heading">
                <span class="prefix"> <strong>@Model.Id</strong></span>
                @title
            </div>
            <div class="panel-body" style="height: 580px; overflow-x: hidden; overflow-y: auto;">
                @Html.AntiForgeryToken()
                <div class="tabbable-line">
                    <ul class="nav nav-tabs ">
                        <li class="active">
                            <a href="#DealBase" data-toggle="tab">
                                基本信息
                            </a>
                        </li>
                        <li>
                            <a href="#DealOpinion" data-toggle="tab">
                                处理意见
                            </a>
                        </li>
                        <li>
                            <a href="#DealFlow" data-toggle="tab">
                                流程图
                            </a>
                        </li>

                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="DealBase" style="overflow-x: hidden; overflow-y: auto;">
                            <table class="table table-form table-dialog-form">
                                <tr>
                                    <th class="w-130px">
                                        <label class="control-label">报销部门：</label>
                                    </th>
                                    <td>
                                        <p class="form-control-static">@Model.ReimburseDepartmentName</p>
                                    </td>

                                    <th>
                                        <label class="control-label">经办人：</label>
                                    </th>
                                    <td>
                                        <p class="form-control-static">@Model.ApplicantName</p>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <label class="control-label">申请情况说明：</label>
                                    </th>
                                    <td colspan="3">
                                        <p class="form-control-static">@Model.ApplyOpinion</p>
                                    </td>
                                </tr>
                            </table>
                            <fieldset>
                                <legend>费用明细</legend>
                                @Html.Action("DetailGrid", new { dailyId=Model.Id })
                            </fieldset>
                            <fieldset>
                                <legend>附件</legend>
                                @Html.Action("Files", "System", new { area = "Auth", resName = nameof(DailyReimburse), resId = Model.Id, allowDelete = false })
                            </fieldset>
                        </div>

                        <div class="tab-pane" id="DealOpinion" style="overflow-x: hidden; overflow-y: auto;">
                            @Html.Action("InstanceTasks", "FlowTask", new { area = "WorkFlow", flowInstanceId = Model.FlowInstanceId })
                        </div>
                        <div class="tab-pane" id="DealFlow" style="overflow-x: hidden; overflow-y: auto;">
                            @Html.Action("TaskImage", "FlowTask", new { area = "WorkFlow", flowInstanceId = Model.FlowInstanceId })
                        </div>

                    </div>
                </div>

                <table class="table table-form table-dialog-form">
                    @if (!currentStep.Uid.Equals(WorkFlowHelper.GetLastStepId(Request.QueryString["flowId"])))
                    {
                        <tr>
                            <th class="w-100px">
                                <label class="control-label">处理意见：</label>
                            </th>
                            <td>
                                <textarea class="form-control" name="workflow_opinion" rows="3"></textarea>
                            </td>
                        </tr>
                    }
                    else
                    {
                        <tr>

                            <th>
                                <label class="control-label">领款人：</label>
                            </th>
                            <td>
                                <div class="input-icon right">
                                    @*<input class="form-control" name="@nameof(Model.ItemName)" value="@Model.ItemName" id="ItemName" type="text" readonly/>*@
                                    <select class="select2-control w-500px form-control" name="@nameof(Model.DrawMoneyId)" id="DrawMoneyId" data-placeholder="请选择领款人">
                                        <option></option>
                                        @Html.AllEmployeeCategoryOptions(Model.DrawMoneyId.ToString());
                                    </select>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label class="control-label">领款金额：</label>
                            </th>
                            <td>
                                <div class="input-icon right">
                                    <input class="form-control" name="@nameof(Model.DrawMoney)" value="@Model.DrawMoney" type="text" />
                                </div>
                            </td>
                        </tr>
                    }
                </table>

            </div>

            <div class="panel-footer text-center">
                <div class="buttons">

                    @if (currentStep.Uid.Equals(WorkFlowHelper.GetLastStepId(Request.QueryString["flowId"])))
                    {
                    <a class="btn btn-outline btn-primary btnWorkFlowCompleted" >
                        <i class="fa fa-check"></i> 完成
                    </a>
                    }
                    else
                    {
                    <a class="btn btn-outline btn-danger btnWorkFlowBack">
                        <i class="fa fa-arrow-left"></i> 驳回
                    </a>

                    <a class="btn btn-outline btn-success btnWorkFlowSend">
                        审核通过
                        <i class="fa fa-arrow-right"></i>
                    </a>
                    }

                    @*<a class="btn btn-default btnClose" onclick="zeniths.util.closeFrameDialog(window);">
                            <i class="fa fa-sign-in"></i> 关闭
                        </a>*@
                </div>
            </div>
        </div>
    </form>
</div>




@section script{
    <script>



        $(function () {
            //$('.editform').dataform().initSelect2().initiCheck().initDatePicker()
            if (zeniths.workflow.instance().workflow_client_model.isLastStep) {
                $('.editform').dataform().initValidate({
                    rules: {
                        DrawMoneyId: {
                            required: true
                        },
                        DrawMoney: {
                            required: true,
                            number: true,
                            min: 1
                        }
                    },
                    messages: {
                        DrawMoneyId: {
                            required: '请选择领款人'
                        },
                        DrawMoney: {
                            required: '请填写领款金额',
                            number: '只能输入数字',
                            min: '不能小于等于0'
                        }
                    },
                    beforeSubmit: function() {
                    }
                });
            }
           
            $('.editform').dataform().initSelect2().initWorkFlow({
                sendCallback: function (wf, result) {
                    //如果下一步骤的处理人是自己 则继续处理下一步骤
                    if (result.url) {
                        window.location.href = result.url;
                    } else {
                        //跳转到待办页面
                        zeniths.util.formAjaxSuccess(result);
                        //window.location.href = '@Url.Action("PendingTasks", "FlowTask", new {area = "WorkFlow"})';
                    }
                }
            }).initAjax({ success: zeniths.util.formAjaxSuccess });

        });
    </script>
}

Zeniths/src/Zeniths.Web/Areas/HR/Views/DailyReimburse/AllGrid.cshtml
@model PageList<DailyReimburse>
@{
    Layout = null;
}
<table class="table table-zeniths table-striped table-bordered table-hover" style="table-layout:fixed">
    <thead>
        <tr>
            <th style="width:34px;">
                <label><input class="checkbox-check" type="checkbox"><span></span></label>
            </th>
            <th data-order="@nameof(DailyReimburse.ReimburseDepartmentName)">所属部门/项目</th>
            <th data-order="@nameof(DailyReimburse.ApplicantName)">经办人</th>
            <th style="width:100px;" data-order="@nameof(DailyReimburse.ApplicationDate)">填报日期</th>
            <th data-order="@nameof(DailyReimburse.ProjectSumMoney)">报销金额</th>
            <th data-order="@nameof(DailyReimburse.ApplyOpinion)">申请情况说明</th>
            <th data-order="@nameof(DailyReimburse.StepName)">当前审批步骤</th>
            <th data-order="@nameof(DailyReimburse.StepStatus)">当前审批状态</th>
            <th data-order="@nameof(DailyReimburse.IsFinish)">审批流程状态</th>

            <th class="text-center" style="width:70px;">操作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var record in Model)
        {
            <tr class="cursor-pointer" data-url="@Url.Action("Details",new {businessId = record.Id})">
                <td>
                    <label><input class="checkbox-check" type="checkbox" value="@record.Id"><span></span></label>
                </td>

                <td>@record.ReimburseDepartmentName</td>
                <td>@record.ApplicantName</td>
                <td>@DateTimeHelper.FormatDate(record.ApplicationDate)</td>
                <td>@record.ProjectSumMoney</td>
                <td>@record.ApplyOpinion</td>
                <td>@record.StepName</td>
                @if (record.StepStatus.HasValue)
                {
                    if (record.StepStatus.Value)
                    {
                        <td>通过</td>
                    }
                    else
                    {
                        <td>不通过</td>
                    }
                }
                else
                {
                    <td></td>

                }
                @if (record.IsFinish)
                {
                    <td>完成</td>
                }
                else
                {
                    <td>未完成</td>
                }

                <td>
                    <a class="btn btn-default btn-xs purple-stripe btnRecordView" data-url="@Url.Action("Details",new {businessId = record.Id})">
                        <i class="fa fa-eye"></i> 查看
                    </a>
                    @*<a class="btn btn-default btn-xs green-stripe btnRecordEdit" data-url="@Url.Action("Edit",new {id = record.Id})">
                            <i class="fa fa-edit"></i> 编辑
                        </a>*@

                </td>
            </tr>
        }
    </tbody>
</table>

@Html.RenderPages(Model)

Zeniths/src/Zeniths.Web/Areas/HR/Views/DailyReimburse/AllIndex.cshtml
@{
    var title = "查看日常费用报销";
}
<div class="container-zeniths">
    <div class="panel panel-default panel-zeniths">
        <div class="panel-heading">
            @title
        </div>
        <div class="panel-body">
            <div class="search-panel-zeniths">
                <form class="form-inline search-form">
                    <div class="form-group">
                        <input class="w-300px form-control" name="name" type="text" placeholder="请输入关键字查询">
                    </div>
                    <div class="form-group">
                        <label>填报日期：</label>
                        <div class="input-group date">
                            <input class="w-150px date-control form-control" name="startDate" placeholder="请输入开始日期">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group date">
                            <input class="w-150px date-control form-control" name="endDate" placeholder="请输入结束日期">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i> 查询
                    </button>
                   
                    @*<a class="btn btn-default" href="@Url.Action("Export")">
                            <i class="fa fa-share-square-o"></i> 导出
                        </a>*@
                </form>
            </div>
            <div class="datagrid" data-url="@Html.Raw(Url.Action("AllGrid"))" data-query-form=".search-form">
            </div>
        </div>
    </div>
</div>

@section script
{
    <script>
        $(function () {
            zeniths.util.standardGridBind({
                editWidth: 950,
                editHeight: 750,
                viewWidth: 950,
                viewHeight: 750
            });
        });
    </script>
}

Zeniths/src/Zeniths.Web/Areas/HR/Views/DailyReimburse/Details.cshtml
@model DailyReimburse
@{
    var title = "查看日常费用报销";
}

<div class="container-edit-zeniths" style="overflow-x: hidden; overflow-y: auto;">
    <form class="editform" action="@Url.Action("Save")" method="POST" role="form">
        <div class="panel panel-default panel-zeniths" style="height: 685px;overflow-x: hidden; overflow-y: auto;">
            <div class="panel-heading">
                <span class="prefix"> <strong>@Model.Id</strong></span>
                @title
            </div>
            <div class="panel-body" style="height: 580px;overflow-x: hidden; overflow-y: auto;">

                <!--tab 代码 开始 -->
                <div class="tabbable-line">
                    <ul class="nav nav-tabs ">
                        <li class="active">
                            <a href="#DealBase" data-toggle="tab">
                                基本信息
                            </a>
                        </li>
                        <li>
                            <a href="#DealOpinion" data-toggle="tab">
                                处理意见
                            </a>
                        </li>
                        <li>
                            <a href="#DealFlow" data-toggle="tab">
                                流程图
                            </a>
                        </li>

                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="DealBase" style="overflow-x: hidden; overflow-y: auto;">
                            <table class="table table-form table-dialog-form">
                                <tr>
                                    <th class="w-130px">
                                        <label class="control-label">报销部门：</label>
                                    </th>
                                    <td>
                                        <p class="form-control-static">@Model.ReimburseDepartmentName</p>
                                    </td>

                                    <th>
                                        <label class="control-label">经办人：</label>
                                    </th>
                                    <td>
                                        <p class="form-control-static">@Model.ApplicantName</p>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <label class="control-label">申请情况说明：</label>
                                    </th>
                                    <td colspan="3">
                                        <p class="form-control-static">@Model.ApplyOpinion</p>
                                    </td>
                                </tr>
                            </table>
                            <fieldset>
                                <legend>费用明细</legend>
                                @Html.Action("DetailGrid", new { dailyId = Model.Id })
                            </fieldset>
                            <fieldset>
                                <legend>附件</legend>
                                @Html.Action("Files", "System", new { area = "Auth", resName = nameof(DailyReimburse), resId = Model.Id, allowDelete = false })
                            </fieldset>
                        </div>

                        <div class="tab-pane" id="DealOpinion" style="overflow-x: hidden; overflow-y: auto;">
                            @Html.Action("InstanceTasks", "FlowTask", new { area = "WorkFlow", flowInstanceId = Model.FlowInstanceId })
                        </div>
                        <div class="tab-pane" id="DealFlow" style="overflow-x: hidden; overflow-y: auto;">
                            @Html.Action("TaskImage", "FlowTask", new { area = "WorkFlow", flowInstanceId = Model.FlowInstanceId })
                        </div>

                    </div>
                </div>
                <!-- tab 代码 结束 -->


            </div>
            <div class="panel-footer text-center">
                <div class="buttons">
                    <a class="btn btn-default btnClose" onclick="zeniths.util.closeFrameDialog(window);">
                        <i class="fa fa-sign-in"></i> 关闭
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
@section script{
    <script>
        $(function() {
            $('#filedatagrid').datagrid();
        });
    </script>
}