Zeniths/src/Zeniths.Web/Areas/Auth/Controllers/SystemUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeniths.Auth.Entity;
using Zeniths.Auth.Service;
using Zeniths.Auth.Utility;
using Zeniths.Extensions;
using Zeniths.Helper;
using Zeniths.Utility;

namespace Zeniths.Web.Areas.Auth.Controllers
{
    //[Authorize]
    public class SystemUserController : AuthBaseController
    {
        private readonly SystemUserService service = new SystemUserService();

        #region private

        /// <summary>
        /// 设置部门实体对象
        /// </summary>
        /// <param name="departmentId">部门主键</param>
        private void SetDepartmentEntity(int departmentId)
        {
            if (departmentId > 0)
            {
                var deptService = new SystemDepartmentService();
                var dept = deptService.Get(departmentId);
                ViewBag.DepartmentEntity = dept;
            }
        }


        #endregion

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取系统部门树节点
        /// </summary>
        public ActionResult GetTree()
        {
            var departmentService = new SystemDepartmentService();
            var dics = departmentService.GetEnabledList();
            var nodes = TreeHelper.Build(dics, p => p.ParentId == 0, (node, instace) =>
            {
                node.IconCls = OrganizeHelper.GetDepartmentIconCls(instace);
            });
            return Json(nodes);
        }

        public ActionResult Grid(string name, string departmentIds)
        {
            var pageIndex = GetPageIndex();
            var pageSize = GetPageSize();
            var orderName = GetOrderName();
            var orderDir = GetOrderDir();
            var list = service.GetPageList(pageIndex, pageSize, orderName, orderDir, name, StringHelper.ConvertToArrayInt(departmentIds));
            return View(list);
        }

        public ActionResult Create()
        {
            var departmentId = Request.QueryString["departmentId"].ToInt();
            return EditCore(new SystemUser
            {
                DepartmentId = departmentId
            });
        }

        public ActionResult Edit(string id)
        {
            var entity = service.Get(id.ToInt());
            return EditCore(entity);
        }

        private ActionResult EditCore(SystemUser entity)
        {
            if (entity == null) throw new ArgumentNullException(nameof(entity), "请指定实体对象");
            SetDepartmentEntity(entity.DepartmentId);
            return View("Edit", entity);
        }

        public ActionResult Details(string id)
        {
            var entity = service.Get(id.ToInt());
            SetDepartmentEntity(entity.DepartmentId);
            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(SystemUser entity)
        {
            var hasResult = service.Exists(entity);
            if (hasResult.Failure)
            {
                return Json(hasResult);
            }
            entity.NameSpell = SpellHelper.ConvertSpell(entity.Name);
            var result = entity.Id == 0 ? service.Insert(entity) : service.Update(entity);
            return Json(result);
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            var result = service.Delete(StringHelper.ConvertToArrayInt(id));
            return Json(result);
        }

        public ActionResult Export()
        {
            return Export(service.GetEnabledList());
        }
    }
}

Zeniths/src/Zeniths.Web/Views/Default/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutBase.cshtml";
    var currentUser = AuthHelper.GetLoginUser();
}
@section style
{
    @Styles.Render("~/easyui-tab-tree-css")
    <link href="~/plugin/jquery-easyui/css/icon.css" rel="stylesheet" />
    <link href="~/assets/css/default.css" rel="stylesheet" />
}
@section script
{
    @Scripts.Render("~/easyui-tab-tree-js")
    <script src="~/Plugin/zeniths.web/js/date.format.js"></script>
    <script src="~/plugin/layer/layer.js"></script>
    <script>layer.config({ extend: 'extend/layer.ext.js' });</script>
    <script src="~/assets/js/default.js"></script>
}
<div class="easyui-layout" fit="true">
    <div data-options="region:'north'" class="header">
        <div class="logo">
            <img src="~/assets/css/images/maintitle.png" alt="Logo">
        </div>

        <div class="topbar">
            <div class="userinfo">
                欢迎您：<span id="userNameInfo">@currentUser.Name</span>&nbsp;
                <span id="IPInfo">@WebHelper.GetClientIP()</span>&nbsp;
                <span id="timeInfo">@DateTimeHelper.FormatDateHasSecond(DateTime.Now)</span>
            </div>
            <ul class="menu">
                <li class="item"><a id="btnUserInfo" data-url="@Url.Action("Details","SystemUser", new { area="Auth",id=currentUser.Id })">个人信息</a></li>
                <li class="item"><a id="btnModifyPassowrd">修改密码</a></li>
                <li class="item"><a id="btnHelper">帮助中心</a></li>
                <li class="item"><a id="btnLogout" href="@Url.Action("Logout")">安全退出</a></li>
            </ul>
        </div>
    </div>
    <div data-options="region:'west',split:true" title="导航菜单" style="width:200px; background-color: #fafafa;">
        <div>
            <ul class="zenithsTree menuTree" data-url="@Url.Action("GetMenuTree")"></ul>
        </div>
    </div>
    <div data-options="region:'center'">
        <div id="tabs" class="easyui-tabs" fit="true" border="false">
        </div>
    </div>
    <div data-options="region:'south'" class="footer">
        操作系统：<span id="statusSystem"></span>&nbsp;&nbsp;
        浏览器：<span id="statusBrowser"></span>&nbsp;&nbsp;
        分辨率：<span id="statusScreen"></span>&nbsp;&nbsp;
        正得信股份 &copy;@DateTime.Now.Year
    </div>
</div> 

Zeniths/src/Zeniths.Web/Views/Default/Login.cshtml
@{
    Layout = "~/Views/Shared/_LayoutBootstrapBase.cshtml";
}

@section style{
    <link href="~/Plugin/jquery-loadmask/css/jquery.loadmask.css" rel="stylesheet" />
    <link href="~/Assets/css/login.css" rel="stylesheet" />
}
@section script{
    <script src="~/Plugin/jquery-loadmask/js/jquery.loadmask.min.js"></script>
    <script src="~/Plugin/layer/layer.js"></script>
    <script src="~/Assets/js/login.js"></script>
}
<div class="loginBackground">
    <div class="container">
        <div class="row" style="margin-top:10%">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="row">
                    <img src="~/Assets/css/images/logo128.png" alt="正得信Logo" />
                </div>
                <div class="row marginBottom40">
                    <span class="loginTitle">
                        正得信股份综合管控平台
                    </span>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="row marginBottom20 has-feedback">
                            <input class="form-control input-lg" id="account" name="account" type="text" placeholder="账号" />
                            <i class="fa fa-user fa-2x form-control-feedback" style="color:#5BC0DE"></i>
                        </div>
                        <div class="row marginBottom20 has-feedback">
                            <input class="form-control input-lg" id="password" name="password" type="password" placeholder="密码" />
                            <i class="fa fa-lock fa-2x form-control-feedback" style="color:#5BC0DE"></i>
                        </div>
                        <div class="row marginBottom20">
                            <input class="btn btn-primary btn-block btn-lg apply_btn" type="submit" value="登 录"
                                   style="font-weight: bold;" data-url="@Url.Action("Login")" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="nl-footer">
                @*<div class="nl-f-nav">推荐系统：win7及以上；推荐浏览器：google,firefox；推荐分辨率：1280*800及以上</div>
                <div class="nl-f-nav">
                    <a href="javascript:void(0);">关于正得信股份</a>|
                    <a href="javascript:void(0);">联系我们</a>|
                    <a href="javascript:void(0);">帮助中心</a>
                </div>*@
                <p class="nl-f-copyright">正得信股份版权所有&copy;2015&nbsp;&nbsp;</p>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-default navbar-fixed-bottom loginfoot"></nav>